# Generated by Django 3.2 on 2023-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
