# Generated by Django 3.2 on 2023-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazifa', '0004_auto_20230730_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
