# Generated by Django 3.2 on 2023-08-01 19:33

from django.db import migrations, models
import wazifa.models


class Migration(migrations.Migration):

    dependencies = [
        ('wazifa', '0007_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=wazifa.models.img_upload),
        ),
    ]
