# Generated by Django 3.2 on 2023-08-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazifa', '0009_auto_20230801_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='wazifa.job'),
            preserve_default=False,
        ),
    ]
